---
  -
    name: Install WSO2 EI BPS 6.1.1
    hosts: test
    become: false

    # Environment variables
    environment:
      # CARBON_HOME: "{{ setup_path }}/wso2ei-6.1.1/wso2/business-process"
      JAVA_HOME: "{{ setup_path }}/jdk1.8.0_131"

    # Task list
    tasks:
      # -
        # name: Test install stuff
        # apt:
        #   name: postgres-client
        #   state: present
      -
        name: Copy pack
        copy:
          src: files/wso2ei-6.1.1.zip
          dest: "{{ setup_path }}/"
      -
        name: Unzip pack
        unarchive:
          src: "{{ setup_path }}/wso2ei-6.1.1.zip"
          dest: "{{ setup_path }}"
      -
        name: Copy JDK
        copy:
          src: "files/jdk-8u131-linux-x64.tar.gz"
          dest: "{{ setup_path }}/"
      -
        name: Untar JDK
        unarchive:
          src: "{{ setup_path }}/jdk-8u131-linux-x64.tar.gz"
          dest: "{{ setup_path }}"
      -
        name: Start WSO2 EI BPS Server
        shell: "bash business-process.sh &"
        args:
          chdir: "{{ setup_path }}/wso2ei-6.1.1/bin/"
          executable: "/bin/bash"
